# Generated by Django 5.2.2 on 2025-06-08 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-createdAt'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='products',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='products',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='products/placeholder.png', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='numReviews',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Reviews'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productbrand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productcategory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productinfo',
            field=models.TextField(blank=True, null=True, verbose_name='Product Information'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productname',
            field=models.CharField(max_length=150, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='stockcount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock Count'),
        ),
        migrations.AlterField(
            model_name='products',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['productname'], name='drf_api_pro_product_f2da71_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['productbrand'], name='drf_api_pro_product_6e0ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['productcategory'], name='drf_api_pro_product_ee14d7_idx'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='drf_api.products'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'user')},
        ),
    ]
