# Generated by Django 5.2.3 on 2025-06-16 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0004_alter_order_options_remove_orderitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='itemsPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 20, 28, 5)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 20, 28, 5)),
        ),
    ]
